Build clean ups.
Don't abuse DEFS.
Use AM_CFLAGS correctly.
Enable in-depth warnings and make them fatal.

git-svn-id: https://svn.callweaver.org/callweaver/trunk@5564 e56c2a57-502e-0410-a6e2-86b2f1ef08c6

diff --git a/utils/cc.in b/utils/cc.in
--- a/utils/cc.in
+++ b/utils/cc.in
@@ -1,11 +1,17 @@
 #!/bin/bash
 
-# If we make warnings fatal we can discard any output from the first run
-@REAL_CC@ "$@" # > /dev/null 2>&1
+tmpfile="/tmp/$$"
+trap "rm -f '$tmpfile'" 0
+
+@REAL_CC@ -Wfatal-errors "$@" > "$tmpfile" 2>&1
 
 if [[ $? -ne 0 ]]; then
-	echo '****'
-	echo '**** Errors encountered, rerunning with -DCW_DEBUG_COMPILE'
-	echo '****'
-	@REAL_CC@ -DCW_DEBUG_COMPILE "$@"
+	if grep 'declaration of ‘__cancel_buf’ shadows a previous local' "$tmpfile" > /dev/null 2>&1; then
+		# There's a nested pthread_cleanup_push...pthread_cleanup_pop
+		@REAL_CC@ -Wfatal-errors "$@" -Wno-shadow
+		[[ $? -eq 0 ]] && exit 0
+	fi
+
+	@REAL_CC@ -DCW_DEBUG_COMPILE "$@" $OVERRIDE_CFLAGS
+	exit 1
 fi
